### ISSUE TITLE
2D memory

### ISSUE THREAD

**Issue by yazdanbakhsh** [stanford-mast/nn_dataflow#1]
What does it mean to have memory nodes are on two sides? (nn_dataflow_search.py)
When the node has the dimension of (1x1) then basically you are adding two node regions for DATA with the same configurations. What does it exactly represent?

Thanks

**Comment by gaomy3832** [comment]
The memory nodes are where the memory interfaces are. If you have 4x4 nodes, the left side memory can be directly accessed by (0, 0), (1, 0), (2, 0), (3, 0), and the right side memory can be directly accessed by (0, 3), (1, 3), (2, 3), (3, 3). All other compute nodes need to go through NoC to access memory.

We assume the input data only come from the left side memory and the output data go to the right side memory (see src/dst_data_region() in core/resource.py), and model weights can come from either ones. When pipelining layers, the two sides can be easily swapped just like double-buffering.

If there is only 1 node, or the width dimension size is 1 (n x 1), basically the two sides overlaps. Physically there is only one set of memory interface. Logically that means this memory serve both input and output, as well as weights.

You may also notice for 3D memory, the src and dst are also the same (all nodes). That has the same meaning, i.e., the same memory serve all types of data.
