### ISSUE TITLE
Unet 

### ISSUE THREAD

**Issue by rishnat** [stanford-mast/nn_dataflow#10]
Tetris has a mechanism in which it checks the dimension of previous layers with respect to current layer and raises a mismatch if there is any. For Unet network, there is first decrease in feature maps and then an increase in feature maps which is not handled right now in Tetris. Is there a way to support Unet model for Tetris or do we need to add that support?

**Comment by gaomy3832** [comment]
The up-conv layer in Unet is not supported currently. Each layer type needs to specify how to map onto the PE array and how to partition across the nodes. Currently there are only two types: `ConvLayer` includes conv and FC layers; `LocalRegionLayer` includes pooling, element-wise, etc.. You either need to find a way to treat up-conv as one of these two, or extend the mapping and partitioning to handle a new type of layer.
