### ISSUE TITLE
Data movement cost of MACs (in conv layer) with low data-reuse 

### ISSUE THREAD

**Issue by Nandan91** [stanford-mast/nn_dataflow#11]
Hi Gao,

Thanks for the nice tool. It helps us a lot in prototyping our ideas. 
One thing that I'm not sure about is: whether this tool appropriately models the data movement cost of MACs with low data-reuse?  For example, MACs in depth-wise convolution have very low data reuse because of the fragmented memory-access. In this tool, cost of any convolution is decided based on the dimensions of convolution layer. Although the dimesnions in depth-wise convolution will be changed (because only one filter channel in filter convolve with a single input feature map),  changing dimesnion would be enough to model the data movement cost or do we need to model some extra relative cost?

**Comment by gaomy3832** [comment]
If you treat the n-channel depth-wise conv layer as one layer, then the computation behavior is different from a normal conv layer. In depth-wise conv, each input channel only contributes to _one_ output channel; in normal conv, each input channel contributes to _all_ output channels. You will have to define a new layer class to model the depth-wise conv layer, and specify its mapping and partitioning behavior.
