### ISSUE TITLE
How to run a single convolutional layer

### ISSUE THREAD

**Issue by rishnat** [stanford-mast/nn_dataflow#12]
Currently for Tetris we need to give network as a python file, which is then parsed to give the results. Is it possible to provide any single layer (can be conv, pool or fc) without providing information about other layers and obtain the results for just that layer?
Currently Tetris checks for mismatch between the current and preceding layers. Will the simulator work correctly if I remove those checks so that I can provide a single layer at a time and obtain results for that 

Thanks

**Comment by gaomy3832** [comment]
Individual layers are OK. I think an easier and more confident way is to just define each layer in an NN using separate single-layer NN python files. Then there should not be any code changes. You just create new files under the `nns` directory as `Net-Conv1.py`, `Net-Conv2.py`, etc..
