### ISSUE TITLE
tiling factors in the output log?

### ISSUE THREAD

**Issue by EmaValpre** [stanford-mast/nn_dataflow#13]
I am trying to understand the size of the feature maps being moved across the memory hierarchy, with the following setup. 
python ./nn_dataflow_search.py --batch 1 --word 16 --array 12 14 --nodes 1 1 --gbuf 110592 --regf 458 --mem-type 2D --disable-bypass i o f --disable-interlayer-opt -t 10 -v vgg_net
These results are for the first conv layer of VGG16. The loop order scheme for DRAM-GBUF scheme seems to be 2 0 1 (Output reuse defined tertris paper).

How can i interpret tvals? what is tb, Output tile factors [tof, toy, tox], Input tile factors [tif, tiy, tix] across spatial and filter dimensions?
tb must be 1 when batch size is 1? Is it happening the same way in the below ouptut?
 
        "tvals": [
          [
            1, 
            64, 
            4
          ], 
          [
            1, 
            1, 
            1
          ], 
          [
            3, 
            1, 
            1
          ]
        ]

        "orders": [
          [
            2, 
            0, 
            1
          ], 
          [
            0, 
            1, 
            2
          ]
        ]

        "ti": [
          1, 
          1, 
          3
        ], 
        "to": [
          64, 
          1, 
          1
        ], 
        "tb": [
          4, 
          1, 
          1
        ], 
        "

**Comment by gaomy3832** [comment]
Please refer to the comments in `LoopBlockingScheme`, i.e., https://github.com/stanford-mast/nn_dataflow/blob/5076d73a8e004ed2c55268e83698347dfedc968c/nn_dataflow/core/loop_blocking_scheme.py#L49-L77

Basically, `ti`, `to`, `tb` are the loop factors of the three loops (input channel, output channel, and batch) from outer level to inner level. `tvals` are the same factors, but organized differently (transposed), first from outer level to inner level, then the three loops.

`orders` indicate within each level, what is the order of the three loops. The three numbers are a permutation of (0, 1, 2). They corresponding to input channel, output channel, and batch loop, corresponding. A number of 0 means the innermost one and 2 means the outermost one. For example, in your case the order is (2, 0, 1), which means the loops from innermost to outmost is output, batch, and input.

**Comment by gaomy3832** [comment]
And for `tb`, you specify batch size is 4, but get `tb` not all 1. This is because there are folding and replication happening at the array mapping level. See the row stationary details in the Eyeriss paper. Here folding is applied, meaning that a large 2D fmap is split into multiple smaller chunks. These chunks are treated as different batches (with the difference of having a halo, i.e., the overlapped parts). Thus the product of `tb` may be larger than your specified batch size.
