### ISSUE TITLE
Temporal schedule in inter-layer pipeline[Gao19]

### ISSUE THREAD

**Issue by Nalilik** [stanford-mast/nn_dataflow#16]
Hi, I am trying to understand the inter-layer pipeline schedule proposed by [Gao19], to my understanding: 
1. Before beam search,  each layer will be grouped to several segments( use itself as 
 the ending layer), and the segment will be checked its validation on data dependency, resource allocation and symbolic scheduling constraints roughly, right? While checking resouce allocation, I found the following comments:
https://github.com/stanford-mast/nn_dataflow/blob/dfb2a3385717a0d69f8164b03bba4abf3ac31ebe/nn_dataflow/core/pipeline_segment.py#L385
Thus I think two adjacent conv layers will not be temporal scheduled in the same region. But my nn-dataflow result on Resnet50 is like that --' segment0=[ conv1_sched_seq=[0,0,0], pool1[0,0,1],conv2_0_a [0,1,0],conv2_0_b[0,1,1],conv2_0_c[0,1,2]];segment1= [conv2_br[1,0,0],conv2_0_res[1,0,1]]...' Does it means that [conv2_0_a ,conv2_0_b,conv2_0_c]can be temporal scheduled in the same region? Could you please give me more details on spatial&temproal schedule rules of inter-layer pipeline? Thanks.
2. What's more, is only two adjacent conv layers exectued by different regions can use ALLO? That is, result like 'pool1[0,0,1],conv2_0_a [0,1,0]' should be pipelining without ALLO, right?
Thank you very much.

**Comment by Nalilik** [comment]
My set up is:
`python ./nn_dataflow_search.py -net resnet50_simple --batch 1 --word 16 --array 8 8 --nodes 16 16 --gbuf 1048576 --regf 64 --mem-type 2D --solve-loopblocking --enable-access-forwarding --basic-interlayer-partition --interlayer-partition -t 2 -v`
(resnet50_simple refers to first 15 layers of resnet50)

**Comment by gaomy3832** [comment]
1. Two adjacent conv layers can be either temporally pipelined or spatially pipelined.

The comment you found is a check for a special case where the segment contains the whole network. In such case, there is no need to time-multiplexing switch between segments (thus the variable name `no_time_mux`), and if all layers are spatial pipelined, basically each layer is mapped to a different region. This is an ideal case of pipelining, in which case you do not need to pay the fill/drain overheads, and if the weights can be fully buffered, you can pin them on-chip. When `no_time_mux` is false, the scheme is still valid, but you just need to re-access the weights each time. Trace the use of `no_time_mux` and you will see how it works.

2. Yes. Only spatially scheduled layers can use ALLO. ALLO basically pipelines the data forwarding between two *simultaneously* executing layers. With temporal scheduled layers, they are executing one after the other.

**Comment by Nalilik** [comment]
Oh, I see. There is a `no_time_mux` condition before. Thanks for the relpy and the explanation on the ideal case of pipelining. : )
