### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by MahdiShokrgozar** [stanford-mast/nn_dataflow#18]
i cant run `python ./nn_dataflow/tools/nn_dataflow_search.py -h`

the error is:
 `Traceback (most recent call last):
  File "./nn_dataflow/tools/nn_dataflow_search.py", line 24, in <module>
    from nn_dataflow.core import NNDataflow
ImportError: No module named nn_dataflow.core
`

**Comment by gaomy3832** [comment]
Try either add `.` to `PYTHONPATH` to let python search for the module, or call it in the way as `python -m` for modules.

**Comment by MahdiShokrgozar** [comment]
thank you

the problem was for my python version.
I ran it with python3 and it was ok.
