### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by yazdanbakhsh** [stanford-mast/nn_dataflow#2]
As far as I understand, for processing the FC layers, the same input is shared among all the PEs. Each PE process this input with different weights and generate different outputs. Right?
If this is true, then each input can be broadcasted to all the PEs. However, in the code, when calculating the global buffer size [**map_strategy.py**, **usize_gbuf = tuple(s * n for s, n in zip(sz_gbuf_unitpass, rcnt))**] you assume that the same input should be replicated with the same number of PE array size. Is there any specific reason for doing this?

**Comment by gaomy3832** [comment]
First, the multiplier `rcnt` is a tuple and we do element-wise multiply to get `usize_gbuf`, so the input is not always replicated with the number of PE array size, but depending on the value of `rcnt[de.IFM]`, which is returned from `_gen_repl()`.

For FC layers, the same input can be shared among different PEs to calculate different output (i.e., I[0] can be multiplied with W[0][0], W[1][0], W[2][0], ... to contribute to O[0], O[1], O[2], ...), or symmetrically, you can also use different input on different PEs to calculate a single output (i.e., I[0], I[1], I[2], ... can be multiplied with W[0][0], W[0][1], W[0][2], ... and sum up to get O[0]). Or you can even do a mix of these two cases.

If we strictly follow Eyeriss row-stationary dataflow, each logic PE set is only 1 PE, so how to balance between the above two cases depends on how to do "replication" of the logic PE sets on the physical PE. We explore all possible replication schemes, as you can see from `_gen_repl()`, by allowing the total value of replication to be distributed between the elements corresponding to input and output in `rcnt` in different ways. So, the mapping in your mind, i.e., sharing the same input among all PEs, has been included.
