### ISSUE TITLE
Other DNN accelerator architecuture support?

### ISSUE THREAD

**Issue by cnjsdfcy** [stanford-mast/nn_dataflow#21]
Dear Professor Gao,

Thanks for creating and sharing this tool.

Is nn_dataflow easy to support dataflow mapping search for other accelerator arch? e.g. NVDLA.
Since I haven't dive into this tool's code yet, I am wondering is it easy to modify the arch definitions or not?

B&R.

**Comment by cnjsdfcy** [comment]
One more question.
As described in alex_net.py, why all the conv layers are splitted into pairs of two?
![image](https://user-images.githubusercontent.com/5670527/90749789-775b4300-e306-11ea-96d2-68795fa1d731.png)

**Comment by gaomy3832** [comment]
Hello,

If you want to extend to other architectures, you mostly need to change the `MapStrategy` class, i.e., have another derived class to process the layer for mapping on the array and eventually output a nested loop structure (as in `NestedLoopDesc` class), which will be the input to the other parts of the scheduler. This `MapStrategy` class is a pretty standalone part from the other parts like loop blocking and layer partitioning, etc.. So it should be not too difficult to do so.

We internally already have the support for TPU-like systolic array, which will be open sourced soon. If you are interested in supporting NVDLA, you are more than welcomed to contribute a pull request. Thanks!

For AlexNet, actually the original AlexNet topology has two branches, as we define here. You can see the original paper for the details. Many recent implementations have simplified this and use an equivalent simple linear chain of layers, which is the more well-known one.

**Comment by cnjsdfcy** [comment]
Dear Professor Gao,

Thanks a lot for your reply, I will see what I can do about NVDLA support after I get a better understanding of the code.
And thanks for the explanation about original AlexNet topology, didn't notice that.

One more question, should the calling of layer.total_ifmap/ofmap_size() in nn_layer_stats.py be corrected like below? Although it didn't impact the results, the args passing are not correct.
![image](https://user-images.githubusercontent.com/5670527/91022389-b69bd380-e627-11ea-9e91-28af8c2f143b.png)

B&R,
Cai Yu

**Comment by gaomy3832** [comment]
Yes you are correct. Feel free to submit a PR that I can merge into the code to fix it.

**Comment by cnjsdfcy** [comment]
Please check the PR.
Close this issue as clearly answered by Professor Gao.
