### ISSUE TITLE
total_ops of ConvLayer

### ISSUE THREAD

**Issue by cnjsdfcy** [stanford-mast/nn_dataflow#23]
Dear Professor Gao,

When calculate the total_ops of ConvLayer as showed below, I think it should be doubled since these are all MAC operations.

https://github.com/stanford-mast/nn_dataflow/blob/198a5274b9529125c6aa2b8b72b365d60cf83778/nn_dataflow/core/layer.py#L220-L222

**Comment by gaomy3832** [comment]
This depends on how you define an "op". For simplicity we just treat one MAC as an op, and the corresponding cost of an op is also for a MAC. If you use flops, then you can multiply the results by 2.

**Comment by cnjsdfcy** [comment]
Understood. So for LocalRegionLayer's "op", they have their own corresponding cost, and are not the same base of MAC op's cost modeling, right?

**Comment by gaomy3832** [comment]
That is a good catch. The ops in local region layers should be cheaper than those in CONV layers. The tool does not capture this difference for now. This might be OK as local region layers contribute very little to the overall ops. But if you care about this issue, you can compensate for it by scaling the number of ops calculated as you suggested here.

**Comment by cnjsdfcy** [comment]
Thanks Professor Gao, this makes sense.
Closing this issue.
