### ISSUE TITLE
the caculation of unit pass

### ISSUE THREAD

**Issue by cqy123456** [stanford-mast/nn_dataflow#3]
In the class MapStrategyEyeriss,
'dim_flpeset = PhyDim2(util.idivc(self.dim_lpeset.h, self.fold.h),util.idivc(self.dim_lpeset.w, self.fold.w))'
and  flpesets in a unitpass = fold.h,
so,as far as i consider,lpeset means batch processing unit_pass fold.w times.
  In function _calc_unitpass，  I think the total accessed size of ITCN is the row size (FIL,IFM,OFM) in one PE × folded PE array size × the number of flpesets in a unitpass .
  I don't understand why using lpeset caculate the accessed size of ITCN (eg:`access[me.ITCN][de.FIL] = acclayer.wfil * self.dim_lpeset.size() * flpesets_per_unitpass`) instead of flpesets,and Does it cause duplicates to multiply by fold.h?
 Can you solve my problem ?
THANKS .

**Comment by gaomy3832** [comment]
I think you are right. When I look at the code now, I cannot find a reason why I used lpeset size there. What you said makes more sense. So I fixed it in commit f176a25dc46fdd4d0d9ee2a06610fe251e1fed2c.
