### ISSUE TITLE
A question of the data size of register file

### ISSUE THREAD

**Issue by cqy123456** [stanford-mast/nn_dataflow#4]
In _init_(...) of class LoopBlockingScheme:
`self.data_size(BL.REGF) > resource.size_regf ` is checking the data size in the register file.
In my understanding, it means that the times of using the same data in the register file(tx2,ty2,tz2)  ×  unit_size[REGF],and procpass is the unit for tx2,ty2,tz2.
And `self.unit_size[BL.REGF] = self.nld.usize_regf`,
However,in class MapStrategyEyeriss, we use the return of _calc_unitpass() to build nld(NestedLoopDes) : 
using CNN layer for example , usize_regf[de.FIL]=sz_regf[de.FIL] = buflayer.wfil & usize_regf[de.IFM]=sz_regf[de.IFM] = buflayer.wfil & usize_regf[de.OFM] sz_regf[de.OFM] = 1,to represent 1D CONV in a PE.
So,in my opinion,when caculating the data size of regf，why not use fold.h × usize_regf to present the size of regf in running a procpass,and then × the run times of procpass in a not change regf (tx2,ty2,tz2).

**Comment by gaomy3832** [comment]
Are you simply asking why the size of regf does not replicate by fold.h? Please see
https://github.com/stanford-mast/nn_dataflow/blob/f176a25dc46fdd4d0d9ee2a06610fe251e1fed2c/nn_dataflow/core/map_strategy.py#L379-L385

If you still have questions, please reopen this.

**Comment by cqy123456** [comment]
I am so sorry to make the question complex. Thanks again for your reply.
But I still have confusion：
After doing the BL.REGF blocking level，the register_file has ti2,to2,tf2 kind of different ifmaps，ofmaps and filters , in the size of sz_regf[de] ?
In one unitpass, one folded fil need  to replace the fmap in regf fold.h times from gbuf ?
Thanks.

**Comment by gaomy3832** [comment]
Yes. This is related to the following lines of code
https://github.com/stanford-mast/nn_dataflow/blob/f176a25dc46fdd4d0d9ee2a06610fe251e1fed2c/nn_dataflow/core/map_strategy.py#L386-L390
where accesses of ifmaps and ofmaps are multiplied by `flpesets_per_unitpass`, which is equal to `fold.h`.

Certainly you can choose the other option if you don't like this one. I don't this Eyeriss paper has explicitly said which one they used. After all, `fold.h` rarely happens given small filter size, so it is not very critical for most NNs.
