### ISSUE TITLE
is there any example to recover the results in [Yang16]?

### ISSUE THREAD

**Issue by blueardour** [stanford-mast/nn_dataflow#6]
Hi, thank you for this wonderful project.
I have a similar idea long ago util I found this project and the related paper.

I want to estimate the optimal dataflow in my custom network. However I don't know how to decide parameters such as  '--op-cost /  hier-cost / hop-cost '.  Could you please provide an example for one of the cases in the nns folder?

Another issue is that in the paper [Yang16], it seems to take Diannao as the baseline, and this project takes the Eyeriss as the base architecture prototype?

**Comment by blueardour** [comment]
Hi, I tried a configuration based on my understanding.
python ./nn_dataflow/tools/nn_dataflow_search.py --batch 1 --word 16 --array 16 16 --nodes 1 1 --gbuf 1572864 --regf 64  --mem-type 2D  -t 5 -v alex_net | tee alex_net.log

However, it seemed a trouble for me to understand the meaning of the output. Is there any guide or document on the result?

**Comment by gaomy3832** [comment]
The parameters of `--op-cost`, etc. specify the relative energy cost of a MAC operation or data access to different memory levels. For example, from the Eyeriss paper [Chen16], `--op-cost` should be 1, and `--hier-cost` should be 200 6 2 1 (see Table IV of the paper). You could find some examples of how to reproduce the results of some papers in the [test](https://github.com/stanford-mast/nn_dataflow/blob/v1.5/nn_dataflow/tests/dataflow_test/test_nn_dataflow.py).

Regarding the output results, there is no document for now. Many of the items are self-explained such as cost and time. `ti`, `to`, and `tb`, and `orders` are the loop blocking factors and orders of the memory levels. `part` is the partitioning scheme. The best place is to read the comments in the source file to understand their format.

This project has not tried to cover everything in [Yang16]. The authors of that paper have their own repo at https://github.com/xuanyoya/CNN-blocking/tree/dev (look at the dev branch). You are welcomed to try it out.
