### ISSUE TITLE
Cannot reporduce results for vgg-net using eyeriss_isscc16 model

### ISSUE THREAD

**Issue by manojrohit** [stanford-mast/nn_dataflow#8]
I am not able to generate latency numbers reported in Table 6, Eyeriss paper in isscc16 journal. I have used the test setup in test_nn_dataflow.py. The numbers are perfect for AlexNet but vgg-16 seems to produce latency proportional to the number of ops which is not the case. 
The authors in Eyeriss paper state that "CONV1-2 and CONV4-2" have same amount of MAC operations former takes nearly four times to process than later. Using the defined dataflow and cost, the latency numbers are similar for both the layers

**Comment by gaomy3832** [comment]
First of all, we are not the authors of Eyeriss, and this tool has not been completely validated or compared with the actual Eyeriss chip. We do not find any complete specifications that allow us to accurately recover the Eyeriss design. We are only trying to provide a reference “row stationary” dataflow. The details are likely to be different from the actual chip.

For AlexNet, the ISCA, ISSCC, and JSSC papers have enough information for us to reverse-engineer the detailed dataflow, so the results match. However for VGG (and other networks), none of these papers has details other than the final numbers, and we cannot know why the results diverge. My guess is that some of these differences are artificial implementation effects that are not tied to the dataflow itself.

I do not remember the statement you refer to. I think intuitively the same number of ops should imply similar throughout. If there are further details about why the latencies are different, I am happy to discuss any fix, or even better, taking bug fix pull requests if you can contribute one :)
