### ISSUE TITLE
How to use the tool for a freshman?

### ISSUE THREAD

**Issue by wxbbuaa2011** [stanford-mast/nn_dataflow#9]
I don't know how to use it. Can you provide some guide?

**Comment by gaomy3832** [comment]
Have you ever read the README and tried to follow the instruction? If not, please do so. If yes, please post the error you see.

**Comment by wxbbuaa2011** [comment]
@gaomy3832 I have run the test as required, but I want to use it to get the test data of each network onEyerss and TETRIS.

**Comment by wxbbuaa2011** [comment]
我想用这个工具，把该工程里面的网络按论文中的数据跑下；更重要的是，我想利用这个工具生成我论文中的对比试验数据。

**Comment by gaomy3832** [comment]
The file `nn_dataflow/tests/dataflow_test/test_nn_dataflow.py` contains a few test cases that help reproduce the results you want. Take a look.

**Comment by wxbbuaa2011** [comment]
@gaomy3832 nn_dataflow_search.py: error: too few arguments. Are these parameters not set to default values? Can you provide a reference example of a command?

**Comment by gaomy3832** [comment]
As I have said, you can find the parameters from the test cases. You can also use `-h` option from the command line to view whether a certain argument is required or not.

**Comment by wxbbuaa2011** [comment]
@gaomy3832 Thank you very much.
